stages:
  - build
  - deploy

build_client-artifacts:
  stage: build
  image: trion/ng-cli
  before_script:
    - cd client
    - npm ci
  script:
    - npm run build
  artifacts:
    expire_in: 7 day
    paths:
      - client/dist/
  only:
    refs:
      - master
      - develop
