stages:
  - build
  - deploy
cache:
  untracked: true
  paths:
    - client/node_modules/
build_client-artifacts:
  stage: build
  image: trion/ng-cli
  before_script:
    - cd client
    - npm ci
  script:
    - npm install
    - npm run build:prod
  artifacts:
    expire_in: 7 day
    paths:
      - client/dist/
  only:
    refs:
      - master
      - develop
